const BASE_STORAGE_KEY = 'recording-mobile-app-v1';
const ACCOUNT_LAST_KEY = 'recording-mobile-last-account';
const LANG_STORAGE_KEY = 'recording-mobile-ui-lang';

const I18N = {
  'zh-Hant': { installApp:'安裝 App', installed:'已安裝', offlineReady:'離線可用', appSubtitle:'手機單頁原型：主頁 → 第二頁 → 第三頁', notLoggedIn:'未登入', loginEmail:'登入 email', logout:'登出', language:'語言', homeSearchPlaceholder:'搜尋主頁分類或第二頁項目', itemSearchPlaceholder:'搜尋第二頁選項', statsGroups:'GROUPS', statsItems:'ITEMS', statsCurrent:'CURRENT', statsHome:'HOME', statsAccount:'ACCOUNT', statsNone:'NONE', noHomeSearchResult:'沒有符合搜尋條件的主頁分類', noGroupHint:'請先從主頁建立分類', noItemSearchResult:'沒有符合搜尋條件的第二頁選項', noItems:'目前沒有第二頁選項', require:'需求', recording:'紀錄', detailPlaceholder:'請先從第二頁選擇項目', detailTitlePlaceholder:'標題', requirePlaceholder:'輸入需求內容', recordingPlaceholder:'輸入紀錄內容', exportJson:'匯出 JSON', importJson:'匯入 JSON', modalCancel:'取消', modalConfirm:'確認', accountTitle:'登入 email', accountCurrentLoggedIn:'目前登入：{email}', accountCurrentLoggedOut:'目前未登入', accountInputPlaceholder:'輸入 email 登入', accountLoginSwitch:'登入 / 切換', addHomeTitle:'新增主頁面選項', addHomeDesc:'請輸入主頁面分類名稱。', addHomePlaceholder:'輸入分類名稱', addItemTitle:'新增第二頁面選項', addItemDesc:'請輸入第二頁面選項名稱。', addItemPlaceholder:'輸入項目名稱', renameHomeTitle:'重新命名主頁面選項', renameHomeDesc:'請輸入新的分類名稱。', renameHomePlaceholder:'輸入新名稱', renameItemTitle:'重新命名第二頁面選項', renameItemDesc:'請輸入新的項目名稱。', renameItemPlaceholder:'輸入新名稱', menuCopy:'複製', menuPaste:'貼上（直接新增已複製的選項）', menuRename:'重新命名', menuDelete:'刪除', invalidEmail:'請輸入有效 email', importNeedLogin:'請先登入 email，才可將內容匯入個人帳戶', importFailed:'匯入失敗，請確認 JSON 格式', invalidJson:'JSON 格式不正確，缺少 groups 陣列' },
  'zh-Hans': { installApp:'安装 App', installed:'已安装', offlineReady:'离线可用', appSubtitle:'手机单页原型：主页 → 第二页 → 第三页', notLoggedIn:'未登录', loginEmail:'登录 email', logout:'登出', language:'语言', homeSearchPlaceholder:'搜索主页分类或第二页项目', itemSearchPlaceholder:'搜索第二页选项', statsGroups:'GROUPS', statsItems:'ITEMS', statsCurrent:'CURRENT', statsHome:'HOME', statsAccount:'ACCOUNT', statsNone:'NONE', noHomeSearchResult:'没有符合搜索条件的主页分类', noGroupHint:'请先从主页建立分类', noItemSearchResult:'没有符合搜索条件的第二页选项', noItems:'目前没有第二页选项', require:'需求', recording:'记录', detailPlaceholder:'请先从第二页选择项目', detailTitlePlaceholder:'标题', requirePlaceholder:'输入需求内容', recordingPlaceholder:'输入记录内容', exportJson:'导出 JSON', importJson:'导入 JSON', modalCancel:'取消', modalConfirm:'确认', accountTitle:'登录 email', accountCurrentLoggedIn:'当前登录：{email}', accountCurrentLoggedOut:'当前未登录', accountInputPlaceholder:'输入 email 登录', accountLoginSwitch:'登录 / 切换', addHomeTitle:'新增主页面选项', addHomeDesc:'请输入主页面分类名称。', addHomePlaceholder:'输入分类名称', addItemTitle:'新增第二页面选项', addItemDesc:'请输入第二页面选项名称。', addItemPlaceholder:'输入项目名称', renameHomeTitle:'重新命名主页面选项', renameHomeDesc:'请输入新的分类名称。', renameHomePlaceholder:'输入新名称', renameItemTitle:'重新命名第二页面选项', renameItemDesc:'请输入新的项目名称。', renameItemPlaceholder:'输入新名称', menuCopy:'复制', menuPaste:'粘贴（直接新增已复制的选项）', menuRename:'重新命名', menuDelete:'删除', invalidEmail:'请输入有效 email', importNeedLogin:'请先登录 email，才可将内容导入个人账户', importFailed:'导入失败，请确认 JSON 格式', invalidJson:'JSON 格式不正确，缺少 groups 数组' },
  'en': { installApp:'Install App', installed:'Installed', offlineReady:'Offline ready', appSubtitle:'Single-page mobile prototype: Home → Page 2 → Page 3', notLoggedIn:'Not signed in', loginEmail:'Sign in email', logout:'Sign out', language:'Language', homeSearchPlaceholder:'Search home groups or page 2 items', itemSearchPlaceholder:'Search page 2 items', statsGroups:'GROUPS', statsItems:'ITEMS', statsCurrent:'CURRENT', statsHome:'HOME', statsAccount:'ACCOUNT', statsNone:'NONE', noHomeSearchResult:'No home groups match the search', noGroupHint:'Create a group from the home page first', noItemSearchResult:'No page 2 items match the search', noItems:'No page 2 items yet', require:'Require', recording:'Recording', detailPlaceholder:'Select an item from page 2 first', detailTitlePlaceholder:'Title', requirePlaceholder:'Enter requirement content', recordingPlaceholder:'Enter recording content', exportJson:'Export JSON', importJson:'Import JSON', modalCancel:'Cancel', modalConfirm:'Confirm', accountTitle:'Sign in email', accountCurrentLoggedIn:'Signed in: {email}', accountCurrentLoggedOut:'Not signed in', accountInputPlaceholder:'Enter email to sign in', accountLoginSwitch:'Sign in / Switch', addHomeTitle:'Add home option', addHomeDesc:'Enter a home group name.', addHomePlaceholder:'Enter group name', addItemTitle:'Add page 2 option', addItemDesc:'Enter a page 2 item name.', addItemPlaceholder:'Enter item name', renameHomeTitle:'Rename home option', renameHomeDesc:'Enter a new group name.', renameHomePlaceholder:'Enter new name', renameItemTitle:'Rename page 2 option', renameItemDesc:'Enter a new item name.', renameItemPlaceholder:'Enter new name', menuCopy:'Copy', menuPaste:'Paste (add copied option directly)', menuRename:'Rename', menuDelete:'Delete', invalidEmail:'Please enter a valid email', importNeedLogin:'Sign in with email before importing into a personal account', importFailed:'Import failed. Check the JSON format', invalidJson:'Invalid JSON format: missing groups array' },
  'ja': { installApp:'アプリをインストール', installed:'インストール済み', offlineReady:'オフライン対応', appSubtitle:'モバイル単一ページ試作：ホーム → 第2ページ → 第3ページ', notLoggedIn:'未ログイン', loginEmail:'メールでログイン', logout:'ログアウト', language:'言語', homeSearchPlaceholder:'ホーム分類または第2ページ項目を検索', itemSearchPlaceholder:'第2ページ項目を検索', statsGroups:'GROUPS', statsItems:'ITEMS', statsCurrent:'CURRENT', statsHome:'HOME', statsAccount:'ACCOUNT', statsNone:'NONE', noHomeSearchResult:'検索条件に一致するホーム分類がありません', noGroupHint:'先にホーム画面で分類を作成してください', noItemSearchResult:'検索条件に一致する第2ページ項目がありません', noItems:'第2ページ項目はまだありません', require:'要件', recording:'記録', detailPlaceholder:'先に第2ページで項目を選択してください', detailTitlePlaceholder:'タイトル', requirePlaceholder:'要件内容を入力', recordingPlaceholder:'記録内容を入力', exportJson:'JSONを書き出す', importJson:'JSONを読み込む', modalCancel:'キャンセル', modalConfirm:'確認', accountTitle:'メールでログイン', accountCurrentLoggedIn:'ログイン中：{email}', accountCurrentLoggedOut:'未ログイン', accountInputPlaceholder:'ログインするメールを入力', accountLoginSwitch:'ログイン / 切替', addHomeTitle:'ホーム項目を追加', addHomeDesc:'ホーム分類名を入力してください。', addHomePlaceholder:'分類名を入力', addItemTitle:'第2ページ項目を追加', addItemDesc:'第2ページ項目名を入力してください。', addItemPlaceholder:'項目名を入力', renameHomeTitle:'ホーム項目を変更', renameHomeDesc:'新しい分類名を入力してください。', renameHomePlaceholder:'新しい名前を入力', renameItemTitle:'第2ページ項目を変更', renameItemDesc:'新しい項目名を入力してください。', renameItemPlaceholder:'新しい名前を入力', menuCopy:'コピー', menuPaste:'貼り付け（コピーした項目を直接追加）', menuRename:'名前変更', menuDelete:'削除', invalidEmail:'有効な email を入力してください', importNeedLogin:'個人アカウントへ読み込む前に email でログインしてください', importFailed:'読み込み失敗。JSON形式を確認してください', invalidJson:'JSON形式が正しくありません。groups 配列がありません' }
};
function makeDefaultData(){return {page:'home',search:'',itemSearch:'',selectedGroupId:'a',selectedItemId:'a1',groups:[{id:'a',name:'a',color:'#2f6297',items:[{id:'a1',title:'aa1',color:'#9ab9ea',require:'adasdad',recording:'asdaafafaf'},{id:'a2',title:'aa2',color:'#9ab9ea',require:'Requirement for aa2',recording:'Recording content for aa2'}]},{id:'b',name:'b',color:'#2f6297',items:[{id:'b1',title:'bb1',color:'#9ab9ea',require:'Requirement for bb1',recording:'Recording content for bb1'}]}]};}
const state={deferredPrompt:null,isInstalled:window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true,uiLang:localStorage.getItem(LANG_STORAGE_KEY)||'zh-Hant',accountEmail:'',page:'home',search:'',itemSearch:'',selectedGroupId:'a',selectedItemId:'a1',copiedPayload:null,longPressTimer:null,longPressTriggered:false,menuTarget:null,modalMode:null,groups:makeDefaultData().groups};
const el={};['appSubtitle','saveStatus','installBtn','avatarBtn','moreBtn','menuDropdown','menuEmailInfo','menuLoginBtn','menuLogoutBtn','menuLangInfo','navTitle','globalSearch','itemSearch','labelGroups','labelItems','labelCurrent','groupCount','itemCount','currentGroupStat','groupGrid','listHeader','listStack','detailTitle','detailRequire','detailRecording','requireLabel','recordingLabel','exportJsonBtn','importJsonBtn','importJsonInput','contextMenu','nameModalBackdrop','nameModalTitle','nameModalDesc','nameModalInput','nameModalCancel','nameModalConfirm','accountModalBackdrop','accountModalTitle','accountCurrent','accountEmailInput','accountLoginBtn','screenHome','screenList','screenDetail'].forEach(id=>el[id]=document.getElementById(id)); el.langOptionButtons=[...document.querySelectorAll('.lang-option')];
const t=(k,v={})=>{let s=(I18N[state.uiLang]||I18N['zh-Hant'])[k]||I18N['zh-Hant'][k]||k; Object.entries(v).forEach(([a,b])=>s=s.replaceAll('{'+a+'}',b)); return s;};
function cloneDefaultData(){return JSON.parse(JSON.stringify(makeDefaultData()));}
function getStorageKeyForAccount(email){return BASE_STORAGE_KEY+'::'+(email||'guest').trim().toLowerCase();}
function applyDataToState(d){const f=cloneDefaultData(); state.page=d?.page||f.page; state.search=typeof d?.search==='string'?d.search:f.search; state.itemSearch=typeof d?.itemSearch==='string'?d.itemSearch:f.itemSearch; state.selectedGroupId=d?.selectedGroupId||f.selectedGroupId; state.selectedItemId=d?.selectedItemId||f.selectedItemId; state.groups=Array.isArray(d?.groups)&&d.groups.length?d.groups:f.groups;}
function getSelectedGroup(){return state.groups.find(g=>g.id===state.selectedGroupId)||state.groups[0]||null;} function getSelectedItem(){const g=getSelectedGroup(); return g?g.items.find(i=>i.id===state.selectedItemId)||g.items[0]||null:null;}
function findGroupById(id){return state.groups.find(g=>g.id===id)||null;} function findItemById(id,gid){const g=gid?findGroupById(gid):getSelectedGroup(); return g?g.items.find(i=>i.id===id)||null:null;}
function getMenuTargetRef(){if(!state.menuTarget) return null; return state.menuTarget.type==='group'?findGroupById(state.menuTarget.id):findItemById(state.menuTarget.id,state.menuTarget.groupId);} 
function getFilteredGroups(){if(!state.search.trim()) return state.groups; const k=state.search.trim().toLowerCase(); return state.groups.filter(g=>g.name.toLowerCase().includes(k)||g.items.some(i=>i.title.toLowerCase().includes(k)));}
function getFilteredItems(){const g=getSelectedGroup(); if(!g) return []; if(!state.itemSearch.trim()) return g.items; const k=state.itemSearch.trim().toLowerCase(); return g.items.filter(i=>i.title.toLowerCase().includes(k));}
function getTotalItems(){return state.groups.reduce((s,g)=>s+(g.items?.length||0),0);} 
function setSaveStatus(text,timeout){el.saveStatus.textContent=text; clearTimeout(window.__saveStatusTimer); if(timeout) window.__saveStatusTimer=setTimeout(()=>el.saveStatus.textContent='LOCAL',timeout);} 
function updateInstallButton(){el.installBtn.textContent=state.isInstalled?t('installed'):t('installApp'); el.installBtn.classList.toggle('visible',!!state.deferredPrompt||state.isInstalled); el.installBtn.disabled=state.isInstalled;}
function persistState(){if(!state.accountEmail){setSaveStatus('NO LOGIN',1100); return;} localStorage.setItem(getStorageKeyForAccount(state.accountEmail),JSON.stringify({page:state.page,search:state.search,itemSearch:state.itemSearch,selectedGroupId:state.selectedGroupId,selectedItemId:state.selectedItemId,groups:state.groups})); localStorage.setItem(ACCOUNT_LAST_KEY,state.accountEmail); setSaveStatus('SAVED',1100);} 
function hydrateState(){try{const remembered=localStorage.getItem(ACCOUNT_LAST_KEY)||''; if(!remembered){applyDataToState(cloneDefaultData()); return;} state.accountEmail=remembered; const raw=localStorage.getItem(getStorageKeyForAccount(remembered)); applyDataToState(raw?JSON.parse(raw):cloneDefaultData());}catch(e){applyDataToState(cloneDefaultData());}}
function normalizeImportedData(parsed){if(!parsed||!Array.isArray(parsed.groups)) throw new Error(t('invalidJson')); const groups=parsed.groups.map((g,gi)=>({id:g.id||`group-import-${Date.now()}-${gi}`,name:g.name||`group-${gi+1}`,color:g.color||'#2f6297',items:Array.isArray(g.items)?g.items.map((i,ii)=>({id:i.id||`item-import-${Date.now()}-${gi}-${ii}`,title:i.title||`item-${ii+1}`,color:i.color||'#9ab9ea',require:i.require||'',recording:i.recording||''})):[]})); return {page:parsed.page||'home',search:parsed.search||'',itemSearch:parsed.itemSearch||'',selectedGroupId:parsed.selectedGroupId||groups[0]?.id||'',selectedItemId:parsed.selectedItemId||groups[0]?.items?.[0]?.id||'',groups};}
function exportJson(){const payload={accountEmail:state.accountEmail,page:state.page,search:state.search,itemSearch:state.itemSearch,selectedGroupId:state.selectedGroupId,selectedItemId:state.selectedItemId,groups:state.groups,exportedAt:new Date().toISOString()}; const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='recording-app.json'; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); setSaveStatus('EXPORTED',1200);} 
function importJsonFile(file){if(!file) return; if(!state.accountEmail){alert(t('importNeedLogin')); el.importJsonInput.value=''; return;} const r=new FileReader(); r.onload=e=>{try{applyDataToState(normalizeImportedData(JSON.parse(e.target.result))); render(); persistState(); setSaveStatus('IMPORTED',1200);}catch(err){alert(err?.message||t('importFailed'));}finally{el.importJsonInput.value='';}}; r.readAsText(file,'utf-8');}
function getAvatarText(){return state.accountEmail?state.accountEmail.trim().charAt(0).toUpperCase()||'?':'?';}
function openAccountModal(){closeMenuDropdown(); el.accountCurrent.textContent=state.accountEmail?t('accountCurrentLoggedIn',{email:state.accountEmail}):t('accountCurrentLoggedOut'); el.accountEmailInput.value=state.accountEmail||''; el.accountModalBackdrop.classList.add('active'); setTimeout(()=>el.accountEmailInput.focus(),10);} function closeAccountModal(){el.accountModalBackdrop.classList.remove('active');}
function loginAccount(){const email=el.accountEmailInput.value.trim().toLowerCase(); if(!email||!email.includes('@')){alert(t('invalidEmail')); return;} state.accountEmail=email; localStorage.setItem(ACCOUNT_LAST_KEY,email); const raw=localStorage.getItem(getStorageKeyForAccount(email)); applyDataToState(raw?JSON.parse(raw):cloneDefaultData()); if(!raw) persistState(); closeAccountModal(); render(); setSaveStatus('ACCOUNT',1200);} function logoutAccount(){state.accountEmail=''; applyDataToState(cloneDefaultData()); localStorage.removeItem(ACCOUNT_LAST_KEY); closeMenuDropdown(); render(); setSaveStatus('LOGOUT',1200);} 
function openMenuDropdown(){el.menuDropdown.classList.add('active'); el.menuEmailInfo.textContent=state.accountEmail||t('notLoggedIn');} function closeMenuDropdown(){el.menuDropdown.classList.remove('active');} function toggleMenuDropdown(){el.menuDropdown.classList.toggle('active'); openMenuDropdown();}
function syncHistoryState(){const m={page:state.page,groupId:state.selectedGroupId,itemId:state.selectedItemId}; const p=history.state; if(!p||p.page!==m.page||p.groupId!==m.groupId||p.itemId!==m.itemId) history.pushState(m,'');}
function openPage(page,pushHistory=true){state.page=page; render(); persistState(); if(pushHistory) syncHistoryState();}
function setSelectedGroup(id,navigate=true){state.selectedGroupId=id; const g=getSelectedGroup(); state.selectedItemId=g?.items?.[0]?.id||''; if(navigate) state.page='list'; render(); persistState(); if(navigate) syncHistoryState();}
function setSelectedItem(id,navigate=true){hideContextMenu(); state.selectedItemId=id; if(navigate) state.page='detail'; render(); persistState(); if(navigate) syncHistoryState();}
function addGroupWithName(name){const clean=(name||'').trim(); if(!clean) return; const g={id:'group-'+Date.now(),name:clean,color:'#2f6297',items:[]}; state.groups.push(g); state.selectedGroupId=g.id; state.selectedItemId=''; state.page='list'; render(); persistState(); syncHistoryState();}
function addItemWithName(name){const g=getSelectedGroup(); const clean=(name||'').trim(); if(!g||!clean) return; const i={id:'item-'+Date.now(),title:clean,color:'#9ab9ea',require:'New requirement',recording:'New recording'}; g.items.push(i); state.selectedItemId=i.id; state.page='detail'; render(); persistState(); syncHistoryState();}
function openNameModal(mode,preset=''){hideContextMenu(); state.modalMode=mode; const cfg={addGroup:{title:t('addHomeTitle'),desc:t('addHomeDesc'),placeholder:t('addHomePlaceholder')},addItem:{title:t('addItemTitle'),desc:t('addItemDesc'),placeholder:t('addItemPlaceholder')},renameGroup:{title:t('renameHomeTitle'),desc:t('renameHomeDesc'),placeholder:t('renameHomePlaceholder')},renameItem:{title:t('renameItemTitle'),desc:t('renameItemDesc'),placeholder:t('renameItemPlaceholder')}}[mode]; if(!cfg) return; el.nameModalTitle.textContent=cfg.title; el.nameModalDesc.textContent=cfg.desc; el.nameModalInput.placeholder=cfg.placeholder; el.nameModalInput.value=preset; el.nameModalBackdrop.classList.add('active'); setTimeout(()=>el.nameModalInput.focus(),10);} function closeNameModal(){el.nameModalBackdrop.classList.remove('active'); state.modalMode=null; el.nameModalInput.value='';}
function confirmNameModal(){const value=el.nameModalInput.value.trim(); if(!value) return; if(state.modalMode==='addGroup') addGroupWithName(value); if(state.modalMode==='addItem') addItemWithName(value); if(state.modalMode==='renameGroup'&&state.menuTarget){const t=getMenuTargetRef(); if(t) t.name=value;} if(state.modalMode==='renameItem'&&state.menuTarget){const t=getMenuTargetRef(); if(t) t.title=value;} closeNameModal(); render(); persistState();}
function copyTarget(){const tRef=getMenuTargetRef(); if(!tRef||!state.menuTarget) return; state.copiedPayload={type:state.menuTarget.type,data:JSON.parse(JSON.stringify(tRef))}; hideContextMenu(); setSaveStatus('COPIED',900);} 
function pasteTarget(){if(!state.copiedPayload||!state.menuTarget) return; if(state.menuTarget.type==='group'){if(state.copiedPayload.type!=='group') return; const clone=JSON.parse(JSON.stringify(state.copiedPayload.data)); clone.id='group-'+Date.now(); clone.name=clone.name+' copy'; clone.items=(clone.items||[]).map((item,index)=>({...item,id:'item-'+Date.now()+'-'+index})); state.groups.push(clone); state.selectedGroupId=clone.id; state.selectedItemId=clone.items[0]?.id||'';} else {if(state.copiedPayload.type!=='item') return; const g=getSelectedGroup(); if(!g) return; const clone=JSON.parse(JSON.stringify(state.copiedPayload.data)); clone.id='item-'+Date.now(); clone.title=clone.title+' copy'; g.items.push(clone); state.selectedItemId=clone.id;} hideContextMenu(); render(); persistState();}
function deleteTarget(){if(!state.menuTarget) return; if(state.menuTarget.type==='group'){state.groups=state.groups.filter(g=>g.id!==state.menuTarget.id); state.selectedGroupId=state.groups[0]?.id||''; state.selectedItemId=state.groups[0]?.items?.[0]?.id||''; if(!state.groups.length) state.page='home';} else {const g=findGroupById(state.menuTarget.groupId); if(g){g.items=g.items.filter(i=>i.id!==state.menuTarget.id); if(state.selectedGroupId===g.id){state.selectedItemId=g.items[0]?.id||''; if(!g.items.length) state.page='list';}}} hideContextMenu(); render(); persistState();}
function renameTarget(){if(!state.menuTarget) return; const ref=getMenuTargetRef(); if(!ref) return; openNameModal(state.menuTarget.type==='group'?'renameGroup':'renameItem', state.menuTarget.type==='group'?ref.name:ref.title);} 
function showContextMenu(x,y,type,ref){state.menuTarget=type==='group'?{type:'group',id:ref.id}:{type:'item',id:ref.id,groupId:getSelectedGroup()?.id||''}; const pasteEnabled=Boolean(state.copiedPayload)&&state.copiedPayload.type===type; el.contextMenu.innerHTML=`<button class="menu-item" data-action="copy">${t('menuCopy')}</button><button class="menu-item ${pasteEnabled?'':'disabled'}" data-action="paste">${t('menuPaste')}</button><button class="menu-item" data-action="rename">${t('menuRename')}</button><button class="menu-item danger" data-action="delete">${t('menuDelete')}</button>`; el.contextMenu.style.left=Math.min(x,window.innerWidth-210)+'px'; el.contextMenu.style.top=Math.min(y,window.innerHeight-250)+'px'; el.contextMenu.classList.add('active'); el.contextMenu.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.getAttribute('data-action'); if(a==='copy') copyTarget(); if(a==='paste'&&pasteEnabled) pasteTarget(); if(a==='rename') renameTarget(); if(a==='delete') deleteTarget();}));}
function hideContextMenu(){el.contextMenu.classList.remove('active'); el.contextMenu.innerHTML=''; state.menuTarget=null;}
function registerLongPress(element,type,ref){const start=(event)=>{if(event.type==='mousedown'&&event.button!==0) return; state.longPressTriggered=false; clearTimeout(state.longPressTimer); const point=event.touches?.[0]||event; state.longPressTimer=setTimeout(()=>{state.longPressTriggered=true; showContextMenu(point.clientX,point.clientY,type,ref);},450);}; const cancel=()=>clearTimeout(state.longPressTimer); element.addEventListener('mousedown',start); element.addEventListener('touchstart',start,{passive:true}); ['mouseup','mouseleave','touchend','touchcancel'].forEach(evt=>element.addEventListener(evt,cancel)); element.addEventListener('contextmenu',e=>{e.preventDefault(); showContextMenu(e.clientX,e.clientY,type,ref);});}
function updateSelectedItem(key,value){const item=getSelectedItem(); if(item) item[key]=value;}
function renderHome(){const groups=getFilteredGroups(); el.groupGrid.innerHTML=''; if(!groups.length){const note=document.createElement('div'); note.className='empty-note'; note.style.gridColumn='1 / -1'; note.textContent=t('noHomeSearchResult'); el.groupGrid.appendChild(note);} else {groups.forEach(group=>{const b=document.createElement('button'); b.className='card'+(state.selectedGroupId===group.id?' active':''); b.type='button'; b.textContent=group.name; b.style.backgroundColor=group.color||'#2f6297'; registerLongPress(b,'group',group); b.addEventListener('click',()=>{if(state.longPressTriggered){state.longPressTriggered=false; return;} setSelectedGroup(group.id,true);}); el.groupGrid.appendChild(b);});} const add=document.createElement('button'); add.className='add-btn'; add.type='button'; add.textContent='+'; add.addEventListener('click',()=>openNameModal('addGroup')); el.groupGrid.appendChild(add);}
function renderList(){const group=getSelectedGroup(); const items=getFilteredItems(); el.listHeader.innerHTML=''; el.listStack.innerHTML=''; if(!group){el.listHeader.innerHTML=`<div class="empty-note">${t('noGroupHint')}</div>`; return;} el.listHeader.innerHTML=`<div style="font-size:22px;font-weight:700;color:#fff;word-break:break-word;text-align:center;">${group.name}</div>`; el.listHeader.style.borderLeft='0'; el.listHeader.style.display='flex'; el.listHeader.style.alignItems='center'; el.listHeader.style.justifyContent='center'; if(!items.length){const note=document.createElement('div'); note.className='empty-note'; note.textContent=state.itemSearch.trim()?t('noItemSearchResult'):t('noItems'); el.listStack.appendChild(note);} else {items.forEach(item=>{const b=document.createElement('button'); b.className='list-item'+(state.selectedItemId===item.id?' active':''); b.type='button'; b.textContent=item.title; b.style.backgroundColor=item.color||'#9ab9ea'; registerLongPress(b,'item',item); b.addEventListener('click',()=>{if(state.longPressTriggered){state.longPressTriggered=false; return;} setSelectedItem(item.id,true);}); el.listStack.appendChild(b);});} const add=document.createElement('button'); add.className='add-btn'; add.type='button'; add.textContent='+'; add.addEventListener('click',()=>openNameModal('addItem')); el.listStack.appendChild(add);}
function renderDetail(){const item=getSelectedItem(); if(!item){el.detailTitle.value=''; el.detailRequire.value=''; el.detailRecording.value=''; el.detailTitle.placeholder=t('detailPlaceholder'); return;} el.detailTitle.value=item.title; el.detailTitle.style.backgroundColor=item.color||'#9ab9ea'; el.detailRequire.value=item.require||''; el.detailRecording.value=item.recording||'';}
function renderNav(){el.avatarBtn.textContent=getAvatarText(); el.navTitle.textContent='Recording'; el.menuEmailInfo.textContent=state.accountEmail||t('notLoggedIn');}
function renderScreens(){el.screenHome.classList.toggle('active',state.page==='home'); el.screenList.classList.toggle('active',state.page==='list'); el.screenDetail.classList.toggle('active',state.page==='detail');}
function renderStats(){const group=getSelectedGroup(); el.groupCount.textContent=String(state.groups.length); el.itemCount.textContent=String(getTotalItems()); el.currentGroupStat.textContent=state.page==='home'?(state.accountEmail?t('statsAccount'):t('statsHome')):(group?.name||t('statsNone'));}
function applyStaticTexts(){document.documentElement.lang=state.uiLang; el.appSubtitle.textContent=t('appSubtitle'); el.globalSearch.placeholder=t('homeSearchPlaceholder'); el.itemSearch.placeholder=t('itemSearchPlaceholder'); el.detailTitle.placeholder=t('detailTitlePlaceholder'); el.detailRequire.placeholder=t('requirePlaceholder'); el.detailRecording.placeholder=t('recordingPlaceholder'); el.exportJsonBtn.textContent=t('exportJson'); el.importJsonBtn.textContent=t('importJson'); el.menuLoginBtn.textContent=t('loginEmail'); el.menuLogoutBtn.textContent=t('logout'); el.menuLangInfo.textContent=t('language'); el.labelGroups.textContent=t('statsGroups'); el.labelItems.textContent=t('statsItems'); el.labelCurrent.textContent=t('statsCurrent'); el.requireLabel.textContent=t('require'); el.recordingLabel.textContent=t('recording'); el.nameModalCancel.textContent=t('modalCancel'); el.nameModalConfirm.textContent=t('modalConfirm'); el.accountModalTitle.textContent=t('accountTitle'); el.accountEmailInput.placeholder=t('accountInputPlaceholder'); el.accountLoginBtn.textContent=t('accountLoginSwitch'); updateInstallButton(); el.langOptionButtons.forEach(btn=>btn.classList.toggle('disabled',btn.dataset.lang===state.uiLang));}
function render(){const groupExists=state.groups.some(g=>g.id===state.selectedGroupId); if(!groupExists&&state.groups.length) state.selectedGroupId=state.groups[0].id; const group=getSelectedGroup(); if(group&&!group.items.some(i=>i.id===state.selectedItemId)) state.selectedItemId=group.items[0]?.id||''; applyStaticTexts(); el.globalSearch.value=state.search; el.itemSearch.value=state.itemSearch; renderNav(); renderScreens(); renderStats(); renderHome(); renderList(); renderDetail();}
async function triggerInstall(){ if(state.isInstalled) return; if(state.deferredPrompt){ state.deferredPrompt.prompt(); const choice=await state.deferredPrompt.userChoice; if(choice?.outcome==='accepted'){state.isInstalled=true; setSaveStatus(t('installed'),1400);} state.deferredPrompt=null; updateInstallButton(); }}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault(); state.deferredPrompt=e; updateInstallButton();}); window.addEventListener('appinstalled',()=>{state.isInstalled=true; state.deferredPrompt=null; updateInstallButton(); setSaveStatus(t('installed'),1400);});
el.globalSearch.addEventListener('input',e=>{state.search=e.target.value; render();}); el.itemSearch.addEventListener('input',e=>{state.itemSearch=e.target.value; render();}); el.detailTitle.addEventListener('input',e=>{updateSelectedItem('title',e.target.value); renderNav(); renderList(); persistState();}); el.detailRequire.addEventListener('input',e=>{updateSelectedItem('require',e.target.value); persistState();}); el.detailRecording.addEventListener('input',e=>{updateSelectedItem('recording',e.target.value); persistState();}); el.installBtn.addEventListener('click',triggerInstall); el.avatarBtn.addEventListener('click',openAccountModal); el.accountLoginBtn.addEventListener('click',loginAccount); el.menuLoginBtn.addEventListener('click',openAccountModal); el.menuLogoutBtn.addEventListener('click',logoutAccount); el.accountEmailInput.addEventListener('keydown',e=>{if(e.key==='Enter') loginAccount();}); el.langOptionButtons.forEach(btn=>btn.addEventListener('click',()=>setUiLanguage(btn.dataset.lang)));
window.addEventListener('popstate',()=>{if(state.page==='detail') openPage('list',false); else if(state.page==='list') openPage('home',false);}); el.moreBtn.addEventListener('click',e=>{e.stopPropagation(); toggleMenuDropdown();}); el.exportJsonBtn.addEventListener('click',exportJson); el.importJsonBtn.addEventListener('click',()=>el.importJsonInput.click()); el.importJsonInput.addEventListener('change',e=>importJsonFile(e.target.files?.[0]||null)); el.nameModalCancel.addEventListener('click',closeNameModal); el.nameModalConfirm.addEventListener('click',confirmNameModal); el.nameModalInput.addEventListener('keydown',e=>{if(e.key==='Enter') confirmNameModal();}); el.nameModalBackdrop.addEventListener('click',e=>{if(e.target===el.nameModalBackdrop) closeNameModal();}); el.accountModalBackdrop.addEventListener('click',e=>{if(e.target===el.accountModalBackdrop) closeAccountModal();}); document.addEventListener('click',e=>{if(!el.menuDropdown.contains(e.target)&&e.target!==el.moreBtn) closeMenuDropdown(); if(!el.contextMenu.contains(e.target)&&!el.nameModalBackdrop.contains(e.target)&&!el.accountModalBackdrop.contains(e.target)) hideContextMenu();});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));}
hydrateState(); render(); history.replaceState({page:state.page,groupId:state.selectedGroupId,itemId:state.selectedItemId},''); console.assert(typeof t==='function','t should be defined'); console.assert(el.navTitle.textContent==='Recording','Title should remain Recording'); console.assert(Array.isArray(state.groups),'Groups should be an array');
